server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/eazybytes_transactions
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "U8dN6z2kFf3LwXq1T7vGj9hYbCeLmZaQ"
  application:
    name: service-transactions
  cloud:
    config:
      uri: http://service-main:8888/config
  config:
    import: configserver:http://service-main:8888/config

eureka:
  client:
    service-url:
      defaultZone: http://service-main:8888/eureka
  instance:
    prefer-ip-address: false
    hostname: service-transactions

management:
  endpoints:
    web:
      exposure:
        include: "*"